AWSTemplateFormatVersion: 2010-09-09
Resources:
  CodeBuildServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub CodeBuildRole-${AWS::StackName}
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service:
                - "codebuild.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: /service-role/
      Policies:
        -
          PolicyName: "CodeBuildAccessPolicies"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Effect: "Allow"
                Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                Resource:
                  - !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/*
              -
                Effect: "Allow"
                Action:
                  - "dynamodb:GetItem"
                  - "s3:ListBucket"
                  - "iam:GetUser"
                Resource:
                  - !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/terraform-state-lock"
                  - !Sub arn:aws:iam::${AWS::AccountId}:user/hands-on.cloud-circleci
                  - "arn:aws:s3:::service.hands-on.cloud"
              -
                Effect: "Allow"
                Action:
                  - "dynamodb:ListTables"
                  - "ec2:DescribeAccountAttributes"
                  - "cloudfront:CreateInvalidation"
                Resource:
                  - "*"
              -
                Effect: "Allow"
                Action:
                  - "s3:GetObject"
                Resource:
                  - "arn:aws:s3:::service.hands-on.cloud/*"
              -
                Effect: "Allow"
                Action:
                  - "s3:*"
                Resource:
                  - "arn:aws:s3:::test.hands-on.cloud/*"
                  - "arn:aws:s3:::origin.hands-on.cloud/*"
                  - "arn:aws:s3:::test.hands-on.cloud"
                  - "arn:aws:s3:::origin.hands-on.cloud"
  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: HandsOnCloud-CodeBuildProject
      BadgeEnabled: true
      ServiceRole: !GetAtt CodeBuildServiceRole.Arn
      Artifacts:
        Type: no_artifacts
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:2.0
      Source:
        Auth:
          Type: OAUTH
        Location: https://github.com/hands-on-cloud/hands-on.cloud.git
        Type: GITHUB
      Triggers:
        Webhook: true
        FilterGroups:
          - - Type: EVENT
              Pattern: PULL_REQUEST_CREATED,PULL_REQUEST_UPDATED
            - Type: BASE_REF
              Pattern: ^refs/heads/master$
              ExcludeMatchedPattern: false
            - Type: ACTOR_ACCOUNT_ID
              Pattern: 12345
              ExcludeMatchedPattern: true
          - - Type: EVENT
              Pattern: PUSH
            - Type: HEAD_REF
              Pattern: ^refs/heads/.*
            - Type: FILE_PATH
              Pattern: READ_ME
              ExcludeMatchedPattern: true
      TimeoutInMinutes: 20
