version: 2.1

orbs:
  node: circleci/node@1.1.6

jobs:
  build:
    docker:
      - image: "cibuilds/hugo:latest"
    environment:
      HUGO_PROD_DOMAIN: "hands-on.cloud"
      HUGO_TEST_DOMAIN: "test.hands-on.cloud"
    steps:
      - checkout
      - run: |
          cd hugo
          if [ "${CIRCLE_BRANCH}" = "master" ]; then
            sed -r -i.bak "s/http:\/\/localhost/https:\/\/${HUGO_PROD_DOMAIN}/g" config.toml
          else
            sed -r -i.bak "s/http:\/\/localhost/http:\/\/${HUGO_TEST_DOMAIN}/g" config.toml
          fi
          hugo -v -d public
      - persist_to_workspace:
          root: ~/
          paths:
            - '*'

  # update_search_index:
  #   executor:
  #     name: node/default
  #     tag: '10.4'
  #   steps:
  #     - attach_workspace:
  #         at: ~/
  #     - node/with-cache:
  #         steps:
  #           - run: npm install
  #     - run: npm run algolia

  deploy:
    docker:
      - image: "cibuilds/hugo:latest"
    environment:
      HUGO_PROD_DOMAIN: "hands-on.cloud"
      HUGO_TEST_DOMAIN: "test.hands-on.cloud"
    steps:
      - run: apt-get update && apt-get -y install git python python-dev python-pip build-essential
      - run: pip install awscli
      - attach_workspace:
          at: ~/
      - deploy:
          name: Deploy to AWS
          command: |
            echo "Adding ads.txt to support AdSense requirements..."
            echo "google.com, pub-2729052102059896, DIRECT, f08c47fec0942fa0" > hugo/public/ads.txt
            if [ "${CIRCLE_BRANCH}" = "master" ]; then
              aws s3 sync hugo/public s3://origin.${HUGO_PROD_DOMAIN} --delete
              aws cloudfront create-invalidation --distribution-id=E2K9OZ801QFKCC --paths /
            else
              aws s3 sync hugo/public s3://${HUGO_TEST_DOMAIN} --delete
            fi

workflows:
  version: 2
  build-test-and-approval-deploy:
    jobs:
      - build
      # - update_search_index:
      #     requires:
      #       - build
      - deploy:
          requires:
            - build
            #- update_search_index
