version: 2
jobs:
  build:
    docker:
      - image: "circleci/node:11.5.0"
    working_directory: ~/src
    environment:
      TERRAFORM_VERSION: 0.11.8
    steps:
      - run: sudo apt-get update
      - run:
          name: install AWS CLI and Terraform
          command: |
            sudo apt-get install -y curl jq python bash ca-certificates git openssl unzip wget python-dev python-pip
            cd /tmp && \
            wget https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip && \
            sudo unzip terraform_${TERRAFORM_VERSION}_linux_amd64.zip -d /usr/bin
            sudo pip install awscli
            cd
      - checkout
      - run: npm install
      - run: gatsby build
      # run tests here
      - deploy:
          name: deploy to AWS
          command: |
            if [ "${CIRCLE_BRANCH}" = "master" ]; then
              aws s3 sync ./public s3://$(terraform output origin_website_bucket) --delete
            else
              echo "Not master branch, dry run only"
            fi
